[TSK-25] add PeepCategoryInputField
bottle-ari/peep_todo_flutter pull request #21
Opened 2023-10-29 15:50 UTC by yachae1101

## 한 일
- PeepCategoryInputField 추가
- PeepEmojiPickerButton 추후 RxString 사용 편의를 위해, condition 변경 null -> "" (empty string)

## 할 일
x

## 장애물
x

2023-10-29 17:35 UTC, Haneol requested changes

2023-10-29 17:35 UTC, Haneol commented on lib/app/views/todo/widget/peep_category_input_field.dart
> +  final ValueChanged<String> onNameChanged;
GetX에서 ValueChanged는 StatefulWidget과 같이 지양하는 것으로 알고 있습니다.
대신 Function<String>으로 변경해주시면 감사하겠습니다.

2023-10-29 17:35 UTC, Haneol commented on lib/app/views/todo/widget/peep_category_input_field.dart
> +            thickness: 1,
thickness 1.h로 수정 부탁드립니다

2023-10-30 09:06 UTC, yachae1101 commented
수정했습니다.

2023-10-30 09:14 UTC, Haneol approved these changes
확인했습니다.

2023-10-30 11:03 UTC, merged